Bump PHP `7.4`, Add `Psalm` and Drop reCaptcha Mailhide
laminas/laminas-recaptcha pull request #22
Opened 2022-04-13 21:45 UTC by ghostwriter

|    Q          |   A
|-------------- | ------
| QA            | yes
| BC break  | yes

### Description

This patch resolves #3, #19 & #20 , via the following changes.

2022-04-13 21:47 UTC, samsonasik commented on src/Response.php
> +final class Response implements ResponseInterface
final should be reverted to avoid BC break

2022-04-13 21:48 UTC, samsonasik commented on src/Response.php
> +    private array $errorCodes = [];
should be reverted to avoid BC break

2022-04-13 21:49 UTC, samsonasik commented on src/Contract/ExceptionInterface.php
> +namespace Laminas\ReCaptcha\Contract;
Please revert as it is BC break

2022-04-13 21:53 UTC, samsonasik commented
This PR seems do 3 things, I think per PR should handle 1 thing instead, and please don't non-private and non-final modifier to avoid BC break

2022-04-13 22:45 UTC, ghostwriter commented
#19 and #20 are related that’s why it’s in the same PR, I just added psalm #3 to get it out of the way, but I understand what you mean.

Let me know what you’re recommending, that I do now.

2022-04-13 22:51 UTC, ghostwriter commented
This Pr is supposed to break BC; maybe targeting the wrong branch though.

2022-04-13 22:53 UTC, samsonasik commented
Probably needs target 4.0.x branch then, let's see if there is opinion from others

2022-04-19 14:57 UTC, Ocramius requested changes
IMO we should split this patch into psalm integration, and 
**then** do the BC breaks separately, with some better design/thought process.

2022-04-19 14:57 UTC, Ocramius commented on src/Contract/ReCaptchaInterface.php
> +interface ReCaptchaInterface
This interface seems to only be extracted, without provided value/clarity :|

2022-04-19 14:57 UTC, Ocramius commented on src/Contract/ResponseInterface.php
> +    public function getErrorCodes(): array;
This interface doesn't seem to provide value: extracting it for the sake of it seems to bring in more BC issues, rather than fixing any

2022-04-19 14:58 UTC, Ocramius commented
Closing this one: let's please chop it into smaller pieces and retry.

2022-04-19 14:58 UTC, closed without merging