Add support for PHP 8.2, drop support for PHP 7.4 and reCaptcha Mailhide
laminas/laminas-recaptcha pull request #28
Opened 2022-11-17 18:52 UTC by ghostwriter

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

- Update composer config `platform.php` to `8.0.99`
- Update composer `PHP` to `~8.0.0 || ~8.1.0 || ~8.2.0`
- Ignore PHP platform requirements via `.laminas-ci.json`
- Drop reCaptcha Mailhide (resolves #19 & #20 )
- Update code to PHP8

2022-11-17 21:01 UTC, gsteel requested changes
Thanks for the patch @ghostwriter - the BC breaks need dealing with but otherwise 👍

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    private array $options = [
This is a BC break because the adapter is open to extension. Please do mark it is `@\final` so it can be improve later on though.

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +        private ?string $ip = null,
BC Break: parameters have to stay `protected` and the types need reverting

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function setHttpClient(HttpClient $httpClient): static
Adding the return type hint is a BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function getHttpClient(): HttpClient
Same here

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function __toString(): string
Return type here is possibly a BC break - not sure 🤔

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function setIp(string $ip): static
BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function getIp(): string
BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function setParam(string $key, string $value): static
BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function setParams(iterable $params): static
BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function getParams(): array
BC break

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    public function getParam(string $key)
OK… I'll stop here. All of the added parameter and return type hints are BC breaks

2022-11-17 21:01 UTC, gsteel commented on src/ReCaptcha.php
> +    private function post(string $responseField): \Laminas\Http\Response
visibility has to stay protected here too

2022-11-17 21:01 UTC, gsteel commented on src/Response.php
> +        private ?HTTPResponse $httpResponse = null
Again, this class is open to extension, so we have to assume it _has_ been extended, therefore visibility changes, parameter type and return type additions need reverting throughout. Feel free to mark as soft final - it means that in the next major we can add the `final` keyword

2022-11-17 21:01 UTC, gsteel commented on src/MailHide.php
> -<?php
As stupid as it sounds, I know the MailHide service has been dead for over 4 years, but to delete this stuff, we'd need to release a new major.

Adding `@\deprecated` now will and reverting the removal will let us get 3.5 out the door

2022-11-18 02:07 UTC, ghostwriter commented on src/ReCaptcha.php
> +    public function __toString(): string
I'm not sure about this one, let me know how to proceed.

2022-11-18 02:15 UTC, samsonasik commented on src/ReCaptcha.php
> +    public function __toString(): string
it is safe to add `string` return type https://3v4l.org/6u9po so the change is valid

2022-11-18 02:39 UTC, ghostwriter commented on src/ReCaptcha.php
> +    public function __toString(): string
Thanks @samsonasik

2022-11-18 09:15 UTC, Ocramius approved these changes
Thanks @ghostwriter!

Thanks for the review, @gsteel!

2022-11-18 09:15 UTC, merged